name: Deploy Next.js App

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: self-hosted  # Run on your GitHub self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Stop Running Container
        run: |
          cd /containers/exirportal
          docker-compose down || true

      - name: Build and Run Next.js App
        run: |
          cd /containers/exirportal
          docker-compose up -d --build

      - name: Cleanup Old Docker Images
        run: docker image prune -f
